services:
  neo4j:
    image: neo4j:community
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
  lexurgy-services:
    build:
      context: ../lexurgy-services
    ports:
      - 8080:8080
    environment:
      - API_KEY=exampleApiKey
